"""Come on man

Revision ID: 928ab529da1b
Revises: af80883b1d68
Create Date: 2025-05-27 13:22:50.951674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928ab529da1b'
down_revision = 'af80883b1d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
